name: Generate Powershell and README

on:
  workflow_dispatch:
  push:
    branches:
      - main
  repository_dispatch:
    types: [file-changed]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Copy windows-install-ubuntu-wsl.ps1
        run: |
          curl -sS https://raw.githubusercontent.com/brettjrea/GitHub_Generate_Readme/main/powershell/windows-install-ubuntu-wsl.ps1 --output windows-install-ubuntu-wsl.ps1
      
      - name: Combine files
        run: |
          toc=$(curl -sS https://raw.githubusercontent.com/brettjrea/GitHub_Generate_Readme/main/readme/generate-readme-table-of-contents.md)
          config=$(curl -sS https://raw.githubusercontent.com/brettjrea/GitHub_Generate_Readme/main/readme/windows-install-ubuntu-wsl.md)
          readme="$(echo -e "${toc}\n---\n${config}")"
          echo "${readme}" > readme.md
          
      - name: Auto commit
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: 'Auto commit copied windows-install-ubuntu-wsl.ps1'
